-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 19, 2022 at 06:45 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movies`
--

-- --------------------------------------------------------

--
-- Table structure for table `movies`
--

CREATE TABLE `movies` (
  `id` int(10) NOT NULL,
  `title` varchar(100) NOT NULL,
  `genre` varchar(20) NOT NULL,
  `release_year` varchar(5) NOT NULL,
  `age` varchar(5) NOT NULL,
  `duration` varchar(20) NOT NULL,
  `synopsis` mediumtext NOT NULL,
  `director` mediumtext NOT NULL,
  `stars` mediumtext NOT NULL,
  `user_comment` mediumtext NOT NULL,
  `comment_date` mediumtext NOT NULL,
  `comment` mediumtext NOT NULL,
  `img` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `movies`
--

INSERT INTO `movies` (`id`, `title`, `genre`, `release_year`, `age`, `duration`, `synopsis`, `director`, `stars`, `user_comment`, `comment_date`, `comment`, `img`) VALUES
(1, 'The Art of Racing in the Rain', 'Drama', '2019', '13+', '1 hr 48 min', 'The movie is a heartfelt tale narrated by a witty and philosophical dog named Enzo. Through his bond with his owner, Denny Swift, an aspiring Formula One driver, Enzo has gained tremendous insight into the human condition.', 'Simon Curtis', 'Kevin Costner, Milo Ventimiglia, Jackie Minns', 'slightlymad2', '29 August 2019', 'I Laughed & Cries', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4362/754362-h'),
(2, 'Gifted', 'Drama', '2017', '13+', '1 hr 41 min', 'Franks plans for a normal school life for Mary are foiled when the seven-year-old mathematical abilities are discovered by Franks formidable mother Evelyn, whose plans for her granddaughter threaten to separate Frank and Mary.', 'Marc Webb', 'Chris Evans, Mckenna Grace, Lindsay Duncan', 'Gordon-11', '22 May 2017', 'I will recommend it to everyone', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/5687/745687-h'),
(3, 'Queen of Katwe', 'Drama', '2016', 'PG', '2 hr 4 min', 'Phiona Mutesi is a small-town girl with big aspirations, but no avenues to explore them because of cultural stereotyping. She gets introduced to a game of chess and her whole life changes as she beats champions and sets out to set a world record.', 'Mira Nair', 'Madina Nalwanga, David Oyelowo, Lupita Nyongo', 'jonbower', '10 October 2016', 'The people are the story', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4369/674369-h'),
(4, 'Ad Astra', 'Drama', '2019', '17+', '2 hr 3 min', 'Astronaut Roy McBride travels to the outer edges of the solar system to find his missing father and unravel a mystery that threatens our planet.', 'James Gray', 'Brad Pitt, Tommy Lee Jones, Ruth Negga', 'MOscarbradley', '2 February 2020', 'A very pleasant surprise', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/1231/1161231-h-a7b4851cda49'),
(5, 'The Martian', 'Drama', '2015', '17+', '2 hr 15 min', 'Mark Watney is presumed dead during a planetary storm and is left behind on planet Mars. NASA discovers that he is not only alive but has also managed to sustain himself. A rescue mission is planned before he runs out of supplies and oxygen.', 'Ridley Scott', 'Matt Damon, Jessica Chastain, Kristen Wiig', 'niutta-enrico', '25 December 2015', 'A Classic by all means', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8265/748265-h'),
(6, 'Million Dollar Arm', 'Drama', '2014', '13+', '2 hr 4 min', 'A sports agent stages an unconventional recruitment strategy to get talented Asian cricket players to play Major League Baseball.', 'Craig Gillespie', 'Jon Hamm, Aasif Mandvi, Alan Arkin', 'blufrog49', '22 May 2014', 'Great Movie, Incredible Story', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8106/748106-h'),
(7, 'The Mountain Between Us', 'Drama', '2017', '17+', '1 hr 51 min', 'Stranded after a tragic plane crash, two strangers must forge a connection to survive the extreme elements of a remote snow covered mountain.', 'Hany Abu-Assad', 'Kate Winslet, Idris Elba, Beau Bridges', 'carchero', '26 December 2018', 'I Like It!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/2727/982727-h'),
(8, 'Miss Peregrines Home for Peculiar Children', 'Drama', '2016', '17+', '2 hr 6 min', 'Jake is astonished when he discovers Peregrines Home for Peculiar Children, a magical school where the residents possess powers. He must protect them from being hunted by their terrifying enemies.', 'Tim Burton', 'Eva Green, Asa Butterfield, Samuel L. Jackson', 'edacheeky', '30 October 2016', 'Delightfully peculiar.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8280/748280-h'),
(9, 'Hidden Figures', 'Drama', '2016', '17+', '2 hr 6 min', 'The film recounts the vital history of a team of black female mathematicians at NASA who helped win the space race against America’s rivals in the Soviet Union and, at the same time, sent the quest for equal rights and opportunity rocketing forwards.', 'Theodore Melfi', 'Taraji P. Henson, Octavia Spencer, Janelle Monáe', 'pamma09', '13 January 2017', 'Excellent representation of the 60s.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8354/748354-h'),
(10, 'The Greatest Showman', 'Drama', '2017', '13+', '1 hr 44 min', 'With his imagination and innovative ideas, P.T. Barnum, an impractical dreamer, decides his own fate, becoming the greatest showman that ever lived.', 'Michael Gracey', 'Hugh Jackman, Michelle Williams, Zac Efron', 'myers-55168', '3 January 2021', 'Viewers get drawn in', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/5359/765359-h'),
(11, 'Jojo Rabbit', 'Comedy', '2019', '17+', '1 hr 48 min', 'A lonely German boy world-view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic. Aided only by his idiotic imaginary friend, Adolf Hitler, Jojo must confront his blind nationalism.', 'Taika Waititi', 'Roman Griffin Davis, Thomasin McKenzie, Scarlett Johansson', 'SnoopyStyle', '22 February 2020', 'one of years best.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8261/748261-h'),
(12, 'Diary of a Wimpy Kid: Rodrick Rules', 'Comedy', '2011', 'PG', '1 hr 35 min', 'Back in middle school after a good summer vacation, Greg Heffley and his older brother Rodrick will have to deal with their parents attempts to have them bond.', 'David Bowers', 'Zachary Gordon, Devon Bostick, Robert Capron', 'jamieleehardy', '27 March 2011', 'Loved it!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/9997/769997-h'),
(13, 'Noelle', 'Comedy', '2019', 'G', '1 hr 39 min', 'When Kris Kringle decides to retire and his son Nick, gets cold feet on Christmas Eve, Noelle must find her brother and bring him back in time to save Christmas.', 'Marc Lawrence', 'Anna Kendrick, Shirley MacLaine, Bill Hader', 'tfrasier-68666', '15 November 2019', 'LIGHT-HEARTED & FUN', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8367/648367-h'),
(14, 'Night at the Museum: Secret of the Tomb', 'Comedy', '2014', '13+', '1 hr 37 min', 'Larry Daley learns that the ancient tablet of Ahkmenrah is dying, which means the end of the magic of the museum. Along with allies, he heads to London to save the museum.', 'Shawn Levy', 'Ben Stiller, Robin Williams, Owen Wilson', 'paulijcalderon', '5 September 2015', 'Glad I saw it', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4209/744209-h'),
(15, 'Why Him?', 'Comedy', '2016', '17+', '1 hr 51 min', 'While his lovers parents are visiting him at his mansion, Laird asks her father, Ned, for his assent to marry her. Disgusted by his behaviour and display of wealth, Ned tries to stop him.', 'John Hamburg', 'Zoey Deutch, James Franco, Tangie Ambrose', 'Top_Dawg_Critic', '13 July 2017', 'a must see!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/9889/1019889-h-99f3f5394428'),
(16, 'Stuber', 'Comedy', '2019', '21+', '1 hr 33 min', 'When a mild-mannered Uber driver named Stu picks up a passenger who turns out to be a cop hot on the trail of a brutal killer, he’s thrust into a harrowing ordeal as he desperately tries to hold onto his wits, his life, and his five-star rating.', 'Michael Dowse', 'Dave Bautista, Kumail Nanjiani, Mira Sorvino', 'nicduffy', '3 October 2019', 'Funny movie with some action', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7998/747998-h'),
(17, 'Isle of Dogs', 'Comedy', '2018', '13+', '1 hr 36 min', 'Mayor Kobayashi has exiled all the canine pets of Megasaki City to a vast garbage dump. Atari sets off to Trash Island in search of his bodyguard-dog, Spots. He begins an epic journey that will decide the fate of the entire Prefecture.', 'Wes Anderson', 'Bryan Cranston, Koyu Rankin, Edward Norton', 'BiiivAL', '7 June 2018', 'A dog is a friend of man', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7984/747984-h'),
(18, 'Can You Ever Forgive Me?', 'Comedy', '2018', '21+', '1 hr 41 min', 'Lee Israel, a best-selling celebrity biographer who finds herself unable to get published because she had fallen out of step with the marketplace, turns her art form to deception, abetted by her loyal friend Jack.', 'Marielle Heller', 'Melissa McCarthy, Richard E. Grant, Dolly Wells', 'PotassiumMan', '10 November 2018', 'Fascinating depiction of serial dishonesty.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/6029/1026029-h-ead785bc21af'),
(19, 'Gnomeo & Juliet', 'Comedy', '2011', 'G', '1 hr 23 min', 'Two garden gnomes, Gnomeo and Juliet, try to find a happy ending to their star-crossed love affair when they are caught up in a feud between neighbours.', 'Kelly Asbury', 'James McAvoy, Emily Blunt, Maggie Smith', 'Fang_33', '12 February 2011', 'Lighten up, really', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8352/748352-h'),
(20, 'The Big Year', 'Comedy', '2011', '13+', '1 hr 40 min', 'The film is about Big Year, a competition among birders, who can spot and identify the highest number of bird species in North America, in a calendar year.', 'David Frankel', 'Owen Wilson, Jack Black, Steve Martin', 'prashanta_guha', '23 January 2012', 'Highly Underrated', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/6541/666541-h'),
(21, 'Pirates of the Caribbean - Salazars Revenge', 'Action', '2017', '13+', '2 hr 9 min', 'Captain Jack Sparrow senses the winds of ill-fortune when his nemesis Captain Salazar escapes from the Devils Triangle, to kill every pirate at sea including him.', 'Joachim Rønning', 'Johnny Depp, Geoffrey Rush, Javier Bardem', 'engagutt_henrik', '23 May 2017', 'I miss the old Jack.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/2371/752371-h'),
(22, 'Terminator: Dark Fate', 'Action', '2019', '17+', '2 hr 7 min', 'Dani Ramos is living a simple life in Mexico City when a highly advanced Terminator, a Rev-9, travels back through time to hunt and kill her. To survive, she joins forces with Grace, a futuristic soldier, and a battle-hardened Sarah Connor.', 'Tim Miller', 'Linda Hamilton, Arnold Schwarzenegger, Mackenzie Davis', 'panthersfreak', '2 November 2019', 'I really enjoyed this movie', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7727/747727-h'),
(23, 'Artemis Fowl', 'Action', '2020', '13+', '1 hr 34 min', 'Artemis Fowl, a 12-year-old genius and descendant of a long line of criminal masterminds, soon finds himself in an epic battle against the powerful underground fairies who may be behind his fathers disappearance.', 'Kenneth Branagh', 'Ferdia Shaw, Lara McDonnell, Josh Gad', 'WatchAndSmile', '15 June 2020', 'Not a bad one', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4364/754364-h'),
(24, 'Guardians Of The Galaxy Vol. 2', 'Action', '2017', '13+', '2 hr 15 min', 'The Sovereign attacks the Guardians when Rocket steals the batteries they are hired to safeguard. Peters father arrives to rescue the Guardians and they set out to discover Peters true parentage.', 'James Gunn', 'Chris Pratt, Zoe Saldana, Dave Bautista', 'SebMoz', '30 November 2020', 'Yes. Just yes.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8248/748248-h'),
(25, 'Star Wars: The Rise of Skywalker', 'Action', '2019', '13+', '2 hr 22 min', 'The surviving members of the resistance face the First Order once again, and the legendary conflict between the Jedi and the Sith reaches its peak, as the landmark Skywalker saga reaches its conclusion.', 'J.J. Abrams', 'Daisy Ridley, John Boyega, Oscar Isaac', 'Dex-ang', '24 April 2020', 'Very Good', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/3113/743113-h'),
(26, 'The Finest Hours', 'Action', '2016', '13+', '1 hr 57 min', 'In February 1952, a massive storm rips an oil tanker in half, leaving its crew of 30 members helpless in more than 70 foot waves, and freezing temperatures. A small life boat and a four-member rescue crew is sent in search of the survivors.', 'Craig Gillespie', 'Chris Pine, Casey Affleck, Ben Foster', 'deloudelouvain', '4 April 2017', 'nice movie', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/1296/901296-h'),
(27, 'John Carter', 'Action', '2012', '13+', '2 hr 12 min', 'Former military captain John Carter finds himself battling a new and mysterious war in the wounded planet of Mars.', 'Andrew Stanton', 'Taylor Kitsch, Lynn Collins, Willem Dafoe', 'jcvdfan83', '15 July 2012', 'John Carter earns more respect!!!!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7128/747128-h'),
(28, 'Togo', 'Action', '2019', 'PG', '1 hr 53 min', 'In the winter of 1925, a champion dogsled trainer and his lead sled dog, Togo, embark on an exhilarating journey across the treacherous terrain of the Alaskan tundra to help transport an antitoxin serum to a small town.', 'Ericson Core', 'Willem Dafoe, Julianne Nicholson, Christopher Heyerdahl', 'Cylac', '21 December 2019', 'Amazing story!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/3785/753785-h'),
(29, 'The Lone Ranger', 'Action', '2013', '13+', '2 hr 23 min', 'John, a lawyer, joins his brother to capture Cavendish, an outlaw, who leaves them for dead, but John is rescued by Tonto, a rebel Comanche. They team up to take down the rogue.', 'Gore Verbinski', 'Johnny Depp, Armie Hammer, William Fichtner', 'Thumper00123', '5 July 2013', 'Incredible.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/5504/935504-h'),
(30, 'Star Wars: The Last Jedi', 'Action', '2017', '13+', '2 h 31 min', 'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares for battle with the First Order.', 'Rian Johnson', 'Daisy Ridley, John Boyega, Mark Hamill', 'anthemlove', '6 December 2019', 'Genius!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/5656/745656-h'),
(31, 'The Lion King', 'Family', '2019', 'PG', '1 hr 58 min', 'In this reimagining of a classic, The Lion King journeys to the African savanna where a young prince overcomes betrayal and tragedy to assume his rightful place on Pride Rock.', 'Jon Favreau', 'Donald Glover, Beyoncé, Seth Rogen', 'dvoon-missy-mcmuffin', '18 July 2019', 'very impressive!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8263/748263-h'),
(32, 'Aladdin', 'Family', '2019', '13+', '2 hr 10 min', 'In this live-action retelling of 1992 classic, Aladdin, a kind-hearted street urchin, and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.', 'Guy Ritchie', 'Will Smith, Mena Massoud, Naomi Scott', 'Chalice_Of_Evil', '23 May 2019', 'A whole new world', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/2687/752687-h'),
(33, 'Maleficent: Mistress of Evil', 'Family', '2019', 'PG', '1 hr 58 min', 'Maleficent and her goddaughter Aurora begin to question their tangled ties as they are pulled in different directions by the impending wedding, unexpected allies, and dark new forces at play.', 'Joachim Rønning', 'Angelina Jolie, Elle Fanning, Harris Dickinson', 'jeddjong', '16 October 2019', 'Battle Royale Disney style', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7989/747989-h'),
(34, 'The Nutcracker and The Four Realms', 'Family', '2018', 'PG', '1 hr 39 min', 'Clara, a young girl, is transported to a mysterious world of gingerbread soldiers and an army of mice.', 'Lasse Hallström', 'Mackenzie Foy, Keira Knightley, Morgan Freeman', 'lauraehrhardt97', '2 November 2018', 'An enjoyable movie.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/6209/956209-h'),
(35, 'Into the Woods', 'Family', '2014', '17+', '2 hr 4 min', 'A baker and his wife wish to have a child but cannot do so due to a curse cast by a witch. To lift the curse, the couple has to obtain four objects that she desperately needs.', 'Rob Marshall', 'Anna Kendrick, Meryl Streep, Chris Pine', 'makingwaves-184-509826', '23 March 2015', 'great film adaptation', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/3581/923581-h'),
(36, 'A Wrinkle In Time', 'Family', '2018', 'PG', '1 hr 45 min', 'After the disappearance of her scientist father, Meg, with her brother and her friend are sent to space to find him.', 'Ava DuVernay', 'Storm Reid, Oprah Winfrey, Reese Witherspoon', 'digitalbeachbum', '1 April 2022', 'The Book Was Better', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4415/874415-h'),
(37, 'Maleficent', 'Family', '2014', '13+', '1 hr 37 min', 'This Sleeping Beauty tale is told from the perspective of the villainous Maleficent and looks at the events that hardened her heart and drove her to curse young Princess Aurora.', 'Robert Stromberg', 'Angelina Jolie, Elle Fanning, Sharlto Copley', 'leonblackwood', '27 October 2014', 'Surprisingly Enjoyable!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7987/747987-h'),
(38, 'Epic', 'Family', '2013', 'G', '1 hr 38 min', 'Mary is transported to a deep forest that is amidst a war between the forces of good and evil. She bands together with a rag-tag group of characters to save both their and her world.', 'Chris Wedge', 'Amanda Seyfried, Josh Hutcherson, Beyoncé', 'Kane20', '29 May 2013', 'Hardly epic', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7079/747079-h'),
(39, 'The Kid Who Would Be King', 'Family', '2019', '13+', '2 hr', 'Alex thinks he’s nobody until he stumbles upon the mythical Sword in the Stone, Excalibur. Now, he must unite his friends and enemies into a band of knights and, together with the legendary wizard Merlin, take on the wicked enchantress Morgana.', 'Joe Cornish', 'Louis Ashbourne Serkis, Denise Gough, Dean Chaumoo', 'english_artist', '6 May 2019', 'Really good fun family film', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8262/748262-h'),
(40, 'The Book of Life', 'Family', '2014', '13+', '1 hr 35 min', 'Manolo sets out on an adventure across three mystical worlds, which will bring him face-to-face with his greatest fears. He has to choose between fulfilling his familys expectations and the love of his life.', 'Jorge R. Gutiérrez', 'Diego Luna, Zoe Saldana, Channing Tatum', 'rgkarim', '19 October 2014', 'Superb Animation', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/2265/822265-h'),
(41, 'Beauty And The Beast', 'Romance', '2017', '13+', '2 hr 9 min', 'Belle, a young woman is taken prisoner by a beast in his castle. Despite her fears, she learns to look beyond the Beasts hideous exterior to realize the kind heart and soul of the true Prince within.', 'Bill Condon', 'Emma Watson, Dan Stevens, Luke Evans', 'drrap', '8 June 2017', 'A classic in its own right.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4371/754371-h'),
(42, 'The Fault in Our Stars', 'Romance', '2014', '17+', '2 hr', 'Hazel and Augustus are teenagers who meet and fall in love at a cancer support group. Hazel, who is attached to an oxygen tank and Gus, who makes jokes about his prosthetic leg find that the relationship takes them on the journey of a lifetime.', 'Josh Boone', 'Shailene Woodley, Ansel Elgort, Nat Wolff', 'Victreebong', '12 June 2014', 'Would happily see this again!', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7980/747980-h'),
(43, 'Lady and the Tramp', 'Romance', '2019', 'G', '1 hr 42 min', 'A timeless re-telling of the 1955 animated classic, Lady, a pampered American Cocker Spaniel and Tramp, a tough but lovable stray, embark on an unexpected adventure and despite their difference, come to understand the value of home.', 'Charlie Bean', 'Tessa Thompson, Justin Theroux, Sam Elliott', 'mary-lyn007', '14 November 2019', 'Not bad', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/7139/747139-h'),
(44, 'The Art Of Getting By', 'Romance', '2011', '13+', '1 hr 23 min', 'George is a high school student and fatalistic loner who has been listed as an academic delinquent because he never does his homework. Things start to look up when he meets Sally but Dustins makes things complicated in Georges life.', 'Gavin Wiesen', 'Freddie Highmore, Emma Roberts, Michael Angarano', 'louis_sound', '8 November 2011', 'Hidden gem.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/old_images/MOVIE/759/1770000759/1770000759-h'),
(45, 'Berhenti Di Kamu', 'Romance', '2021', '13+', '1 hr 40 min', 'Doctor Gia searches for the meaning in life through extraordinary events in the ER where he works.', 'Indra Gunawan', 'Roger Danuarta, Cut Meyriska, Salshabilla Adriani', 'abc123', '22 December 2021', 'Good.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4286/854286-h'),
(46, 'Broken Hearts', 'Romance', '2012', '13+', '1 hr 32 min', 'Olivias life feels empty after her boyfriend, Jamie disappears. She has a hard time trusting anyone, even when she meets Aryo, Jamies friend. Problems arise when Jamie finds out Aryo is truly in love with her.', 'Helfi C.H. Kardit', 'Julie Estelle, Reza Rahadian, Darius Sinathrya', 'def456', '11 November 2012', 'Ok.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/9458/739458-h'),
(47, 'Incredible Love', 'Romance', '2021', '13+', '1 hr 45 min', 'Abhimanyu was born a savant, diagnosed as autistic, and with the uncanny ability to hear voices remotely.', 'Hendra Martono', 'Egy Fedly, Irsyadillah, Roy Marten', 'ghi789', '22 December 2021', 'Superb.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/8687/888687-h'),
(48, 'Negeri Van Oranje', 'Romance', '2015', '17+', '1 hr 35 min', 'A story of a bond shared between five best friends. The journey to find meaning in life, to discover their dreams, to overcome their struggles and to seek love in a foreign country, the Netherlands.', 'Endri Pelita', 'Tatjana Saphira, Chicco Jerikho, Abimana Aryasatya', 'callistoceres', '15 March 2018', 'Mediocre love story', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/4447/734447-h'),
(49, 'Perahu Kertas Part 1', 'Romance', '2012', '13+', '1 hr 51 min', 'Tidal relationship between Keenan and Kugi becoming good friends. As they try to achieve their dreams, they are faced with a stretch of mystery and obstacles. Will their hearts and dreams meet?', 'Hanung Bramantyo', 'Maudy Ayunda, Adipati Dolken, Reza Rahadian', 'andrirandom', '1 May 2019', 'beautiful slice of life story', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/9801/739801-h'),
(50, 'Perahu Kertas Part 2', 'Romance', '2012', '13+', '1 hr 41 min', 'Sequel to Perahu Kertas Part 1. Kugy and Keenan are reunited. Living new chapters of their lives, how will they deal with new commitments and relationships?', 'Hanung Bramantyo', 'Maudy Ayunda, Adipati Dolken, Reza Rahadian', 'averpix', '16 April 2013', 'Ok.', 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/9806/739806-h');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `movies`
--
ALTER TABLE `movies`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
